### ISSUE TITLE
It not really an issue, more of a question.

### ISSUE THREAD

**Issue by kerike** [shannah/CN1Sockets#2]
Hi,

first of all, great work. Thank you for your lib. I am coming from an as3 background, and I have some problems connecting to my java server. Connecting to it with as3 is really easy, but I have some problems using this lib.

This is my code:

public class CustomSocket extends Thread 
{
    private Socket _socket;
    
    private String _ip;
    private int _port;
    
    private boolean running = false;
    private int bufferSize = 2048;
    
    public CustomSocket(String ip, int port)
    {
        _ip = ip;
        _port = port;
    }
    
    public void connect()
    {
        try 
        {
            if (Socket.isSocketSupported())
            {
                Log.p("Socket started!");
                _socket = new Socket(_ip, _port, 30);
                this.start();
            }
            else
                Log.p("Socket not supported!");
        }
        catch ( Exception ex)
        {
            Log.p("We have an error");
            Log.e(ex);

        }
    }
    
    public void stopSocket()
    {
        running = false;
        this.interrupt();
    }
    
    @Override
    public void run()
    {
        running = true;
        while( running )
        {
            try
            {
                //_socket.getOutputStream().write("ping\n\0".getBytes());
                
                byte[] buffer = new byte[bufferSize];
                int offset = 0;
                int bytesRead = _socket.getInputStream().read(buffer, offset, bufferSize);
                Log.p(Integer.toString(bytesRead) + " " + Integer.toString(offset));
                
                while (bytesRead != -1)
                {
                    Log.p(new String(buffer));
                    
                    offset += bytesRead;
                    bytesRead = _socket.getInputStream().read(buffer, offset, bufferSize);
                    Log.p(Integer.toString(bytesRead) + " " + Integer.toString(offset));
                }
                
                Log.p("Socket closed normaly!!!");
                _socket.shutdownInput();
                _socket.shutdownOutput();
                _socket.close();
            }
            catch ( Exception ex)
            {
                running = false;
                Log.p("Socket closed because of exception!!!");
                Log.e(ex);
            }
        }
    }
}

The problem I am having, is that the connection closes after the first read. Do you have any idea why is that?

Thank you very much for your help.

**Comment by shannah** [comment]
Does it ever enter the "while (bytesRead != -1)" loop?  It looks like you might have a problem in there with the offset.  You are increasing the offset on each iteration without consideration of what happens when it is greater or equal to bufferSize.

**Comment by kerike** [comment]
Hi shannah,

thanks for replying. I will show you my logs. This is a simple app, I didn't want to process the incoming data...I just wanted to see if it works, because the rest of my app depends on this working perfectly.

[EDT] 0:0:0,0 - Socket started!
[Thread-4] 0:0:0,391 - 698 0
[Thread-4] 0:0:0,391 - the actual data, sorry I can not show you that :)
[Thread-4] 0:0:0,469 - -1 698
[Thread-4] 0:0:0,469 - Socket closed normaly!!!
[Thread-4] 0:0:0,484 - Socket closed because of exception!!!

So I make the first read. I read 698 bytes of data...the buffer is 2048. The second read returns -1. Then it writes out Log.p("Socket closed normaly!!!");. But when I want to close the socket, it gives me an exception, because the socket is already closed.

Could the problem be that I am connecting to the server where the as3 socket is connecting? And for as3 every message must be ended with \0. Does sending the \0 character at the end of a message close the java socket?

Thank you very much for your time and help.

**Comment by shannah** [comment]
Is this on a device or in the simulator?  Can you post the stack trace?  I
don't think the '\0' character should be a problem, but I suppose it's
possible.

On Sat, Feb 28, 2015 at 6:43 AM, kerike <notifications@github.com> wrote:

> Hi shannah,
>
> thanks for replying. I will show you my logs. This is a simple app, I
> didn't want to process the incoming data...I just wanted to see if it
> works, because the rest of my app depends on this working perfectly.
>
> [EDT] 0:0:0,0 - Socket started!
> [Thread-4] 0:0:0,391 - 698 0
> [Thread-4] 0:0:0,391 - the actual data, sorry I can not show you that :)
> [Thread-4] 0:0:0,469 - -1 698
> [Thread-4] 0:0:0,469 - Socket closed normaly!!!
> [Thread-4] 0:0:0,484 - Socket closed because of exception!!!
>
> So I make the first read. I read 698 bytes of data...the buffer is 2048.
> The second read returns -1. Then it writes out Log.p("Socket closed
> normaly!!!");. But when I want to close the socket, it gives me an
> exception, because the socket is already closed.
>
> Could the problem be that I am connecting to the server where the as3
> socket is connecting? And for as3 every message must be ended with \0. Does
> sending the \0 character at the end of a message close the java socket?
>
> Thank you very much for your time and help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shannah/CN1Sockets/issues/2#issuecomment-76528651>.
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by kerike** [comment]
This is on the simulator.
First stack trace:

java.io.IOException: Socket is closed
	at ca.weblite.codename1.net.Socket$SocketOutputStream.close(Socket.java:242)
	at ca.weblite.codename1.net.Socket.shutdownOutput(Socket.java:150)
	at com.mycompany.myapp.CustomSocket.run(CustomSocket.java:86)

So i edited out the code:  _socket.shutdownOutput(); 
And now it crashes here:

java.io.IOException: Socket is closed
	at ca.weblite.codename1.net.Socket$SocketInputStream.read(Socket.java:207)
	at com.mycompany.myapp.CustomSocket.run(CustomSocket.java:69)

It crashes on the read...
